### PR TITLE
accounts models, views, and routes

### PR DESCRIPTION
**Pull request by Mxia09**
PostgreSQL DB connected to the server. New accounts directory created for organization for accounts model, views file to handle logic of a particular route, and routes to handle http requests

### CODE REVIEW

**Comment by Mxia09** [comment]
`.venv ` has now been moved from server to root directory gitignore. Thanks for catching that!

**Comment by bkeys818** [comment]
Oh, wait, I found the issue. You've created the `.venv` in the root. Activate the environment in the client directory, and you should be fine. If you need @Mxia09 or I to talk you through it, we can.

**Comment by Mxia09** [comment]
`.venv` moved to server side

**Review by rayansattarkhan — APPROVED** [review]
Looks good. Approved.

**Pull request merged**
