### PR TITLE
Header UI

### PR DESCRIPTION
**Pull request by Kyle-Oneill20**
same as before but current master branch files

### CODE REVIEW

**Comment by bkeys818** [comment]
What did you do for this commit? -> [16fb482](https://github.com/DrivenIIDevelop/Pokemon/pull/25/commits/16fb4829d17dfc996fb51cc2eea52419c18e1e57)

Was it a normal merge? A squash merge?

**Comment by Kyle-Oneill20** [comment]
@bkeys818 I believe it was just a normal commit. I didn’t do anything from any of the other commits.

**Comment by DRD161** [comment]
@Kyle-Oneill20 how did you update your branch with master? I don't see a merge in the Git history.

**Comment by Kyle-Oneill20** [comment]
@DRD161 I downloaded an up-to-date zip file from the master files on GitHub and used those files to overwrite the folder of the same name.

**Review by bkeys818 — CHANGES_REQUESTED** [review]
Once we hop on that call and figure out the merge, we'll be all good!

**Pull request closed without merging**
